# Project information
site_name: Digital Education at Cardiff University
# site_url:
# site_author:
# site_description: >-
#   This is a documentation site for the Digital Education team at Cardiff
#   University. Here you will find information on how to use the Learning Central, as well as general information on how to use various Digital Education tools we support.
# site_keywords: Cardiff University, Digital Education, Learning Central, Blackboard, Turnitin, Panopto, Ultra, Essentials, Guides, Tutorials, Help, Support, Information, Documentation
# site_favicon: assets/images/favicon.ico
edit_uri: edit/main/docs/

# Repository
repo_name: dandange8005/ultra-Essentials
repo_url: https://github.com/dandange8005/Ultra-Essentials

# Copyright
# copyright: © 2021 Cardiff University

# Navigation settings
nav:
  - Home: index.md
  - Getting Started:
    - Base Navigation: getting-started/base-navigation.md
    - Navigating inside an Ultra course: getting-started/nav-inside-course.md
    - Personal Profile: getting-started/personal-profile.md
    - Course Staff List: getting-started/module-staff.md

  - Building Your Course:
    - Learning Modules and Folders: building-course/learning-modules-folders.md


  - MKDocs: 
    - mkdocs/index.md
    - Basic Markdown: mkdocs/basic-markdown.md
    - Buttons: mkdocs/buttons.md
    - Call out: mkdocs/callouts.md
    - Grids: mkdocs/grids.md
    - Icons and Emojis: mkdocs/icons-emojis.md
    - Images: mkdocs/images.md
    - Multimedia: mkdocs/multimedia-embedding.md
    - Tabs: mkdocs/tabs.md
    - Tasks List: mkdocs/tasks-list.md


# Theme settings

theme:
  name: material
  logo: assets/images/Cardiff-Logo-Red-Inversed.svg
  custom_dir: docs/overrides
  features:
    - navigation.tabs # Navigation tabs at the top
    - navigation.tabs.sticky # Fixed navigation tabs while scrolling
    - navigation.top # "Back to top" button
    - navigation.footer # Previous/next page links in footer
    # - navigation.sections # Sidebar sections (disabled)
    - navigation.expand # Expand all navigation sections
    - navigation.indexes # Enable section index pages
    - navigation.path # Show current page path
    - toc.follow # Scrolling table of contents
    # - toc.integrate # Sidebar table of contents (disabled)
    - search.suggest # Search with suggestions
    - search.highlight # Highlight search matches
    - search.share # Share search results
    # - content.tabs.link # Link content tabs (disabled)
    - content.code.annotate # Code block annotations
    - content.code.copy # Copy button for code blocks
    # - content.action.edit # Edit page button (disabled)
    # - content.action.view # View page button (disabled)
    - content.image.zoom # Zoom images
    - content.tooltips # Tooltips for links
    - announce.dismiss # Dismiss announcement banner

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom #CU branding - red
      accent: custom  #CU branding - black

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: custom #CU branding - red
      accent: indigo
  
  # main typography
  font:
    text: Inter
    code: Roboto Mono

# Plugins
plugins:
  - search: # Search plugin
      lang: 
        - en
      separator: '[\s\-\.]+'
  - i18n: # Internationalization
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: cy
          name: Cymraeg
          build: true
      docs_structure: suffix
      reconfigure_material: true
      reconfigure_search: true
  - roamlinks # Roam Research links
  - git-revision-date-localized # Git revision date
  - mkdocs-video:
      css_style:
        width: "100%"
        aspect-ratio: "16/9"


# Additional CSS
extra_css:
  - https://unpkg.com/open-props # OpenProps
  - stylesheets/extra.css # Custom CSS

# Extra Javascript
extra_javascript:
  #- javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 


# Extra Markdown Extensions
markdown_extensions:
  # Python Markdown
  - abbr # Abbreviations
  - admonition # Admonitions
  - attr_list # Attribute lists
  - def_list # Definition lists
  - footnotes # Footnotes
  - md_in_html # Markdown in HTML
  - toc:
      permalink: true
      toc_depth: 3  # This will show up to third-level (H3) headings
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets

# Exclude files
draft_docs: |
  drafts/

# Additional configuration
extra:
  status: 
    new: Recently added
  alternate:
    - name: English
      link: /
      lang: en
    - name: Cymraeg
      link: /cy/
      lang: cy
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.