# Site Information
site_name: Digital Education at Cardiff University
repo_url: https://github.com/dandange8005/ultra-essentials
repo_name: dandange8005/ultra-essentials
edit_uri: edit/main/docs/

# Navigation settings

# Theme settings

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    # - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    # - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.image.zoom
    - announce.dismiss

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom #CU branding - red
      accent: custom  #CU branding - black

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: custom #CU branding - red
      accent: indigo
  
  # main typography
  font:
    text: Inter
    code: Roboto Mono

# Plugins
plugins:
  - search:
      lang: 
        - en
      separator: '[\s\-\.]+'
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: cy
          name: Cymraeg
          build: true
      docs_structure: suffix
      reconfigure_material: true
      reconfigure_search: true
  - roamlinks
  - git-revision-date-localized


# Additional CSS
extra_css:
 - stylesheets/extra.css

# Extra Javascript
extra_javascript:
  #- javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 


# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.magiclink
  - pymdownx.details
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Cookies consent
extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Cymraeg
      link: /cy/
      lang: cy
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.